commerce_giftcard.giftcard_type.*:
  type: config_entity
  label: 'Commerce Gift card type config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'

commerce_checkout.commerce_checkout_pane.commerce_giftcard_redemption:
  type: commerce_checkout_pane_configuration
  mapping:
    allow_multiple:
      type: boolean
      label: 'Allow multiple coupons'
