on:
  push:
  pull_request:

name: PHPStan

jobs:
  phpstan:
    name: PHPStan

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: PHPStan
        run: composer install && ./vendor/bin/phpstan analyse .
